# Generated by Django 4.2.20 on 2025-04-07 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0026_merge_20250224_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='certification.certificatetype'),
        ),
    ]
