# Generated by Django 4.2.20 on 2025-04-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0027_certificate_certificate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='certifyingorganisation',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Is this organisation archived?'),
        ),
        migrations.AddField(
            model_name='historicalcertifyingorganisation',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Is this organisation archived?'),
        ),
    ]
