# Generated by Django 4.2.20 on 2025-05-08 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0028_certifyingorganisation_is_archived_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditsOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_requested', models.IntegerField(help_text='Number of credits requested in the order')),
                ('credits_issued', models.BooleanField(default=False, help_text='Flag to indicate if credits have been issued')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the payment was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the payment was last updated')),
                ('organisation', models.ForeignKey(help_text='The certifying organisation that placed the order', on_delete=django.db.models.deletion.CASCADE, related_name='credits_orders', to='certification.certifyingorganisation')),
            ],
        ),
    ]
