# Generated by Django 4.2.20 on 2025-07-14 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_alter_project_accent_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="changelog_managers",
        ),
        migrations.RemoveField(
            model_name="project",
            name="is_changelogs",
        ),
        migrations.RemoveField(
            model_name="project",
            name="is_lessons",
        ),
        migrations.RemoveField(
            model_name="project",
            name="is_sustaining_members",
        ),
        migrations.RemoveField(
            model_name="project",
            name="is_teams",
        ),
        migrations.RemoveField(
            model_name="project",
            name="lesson_managers",
        ),
        migrations.RemoveField(
            model_name="project",
            name="sponsorship_managers",
        ),
        migrations.RemoveField(
            model_name="project",
            name="sponsorship_programme",
        ),
    ]
